version = 1

[[annotations]]
path = [
  ".audit/**/",
  ".github/workflows/**/",
  ".gitignore",
  ".soldeerignore",
  "audit/**/",
  "README.md",
  "flake.lock",
  "flake.nix",
  "foundry.toml",
  "remappings.txt",
  "slither.config.json",
  "REUSE.toml",
  "src/lib/LibCodeGen.sol",
  "soldeer.lock",
]
SPDX-FileCopyrightText = "Copyright (c) 2020 Rain Open Source Software Ltd"
SPDX-License-Identifier = "LicenseRef-DCL-1.0"
