// SPDX-License-Identifier: LicenseRef-DCL-1.0
// SPDX-FileCopyrightText: Copyright (c) 2020 Rain Open Source Software Ltd
pragma solidity =0.8.25;

import {Test} from "forge-std-1.16.1/src/Test.sol";
import {LibCodeGen} from "src/lib/LibCodeGen.sol";

/// @title LibCodeGenFilePrefixTest
contract LibCodeGenFilePrefixTest is Test {
    /// The prefix must not name the script that generates the file. Each
    /// consumer names its own build script, so any script path here is a claim
    /// this library cannot keep. Asserted as "names no Solidity file at all"
    /// because the constraint is that no script is named, not that some
    /// particular name is absent.
    function testFilePrefixNamesNoScript() external pure {
        assertFalse(vm.contains(LibCodeGen.filePrefix(), ".sol"), "prefix names a script");
    }

    /// The prefix heads every generated file in every consumer repo, so a
    /// change here rewrites committed files org wide. Pinned exactly so that
    /// lands as a deliberate, reviewable diff rather than a surprise on the
    /// next regeneration.
    function testFilePrefixExact() external pure {
        //REUSE-IgnoreStart
        assertEq(
            LibCodeGen.filePrefix(),
            "// SPDX-License-Identifier: LicenseRef-DCL-1.0\n"
            "// SPDX-FileCopyrightText: Copyright (c) 2020 Rain Open Source Software Ltd\n"
            "pragma solidity ^0.8.25;\n\n" "// THIS FILE IS AUTOGENERATED BY THE BUILD SCRIPT. DO NOT EDIT BY HAND.\n\n"
            "// It is committed to the repository because there is a circular dependency\n"
            "// between the contract and its generated file. The contract needs the\n"
            "// generated file to exist so that it can compile, and the generated file\n"
            "// needs the contract to exist so that it can be compiled.\n"
        );
        //REUSE-IgnoreEnd
    }
}
