// SPDX-License-Identifier: LicenseRef-DCL-1.0
// SPDX-FileCopyrightText: Copyright (c) 2020 Rain Open Source Software Ltd
pragma solidity =0.8.25;

import {Test} from "forge-std-1.16.1/src/Test.sol";
import {LibFs} from "src/lib/LibFs.sol";
import {CodeGennable} from "test/concrete/CodeGennable.sol";

/// @title LibFsBuildFileForContractTest
/// @notice `buildFileForContract` is the only thing in this repo that touches
/// disk. What it writes is Solidity source that a consumer commits and imports,
/// so these assert the exact bytes of the file on disk, at the exact path, for
/// the whole file rather than for a fragment of it.
///
/// The expected content is rebuilt here from the literal text and from
/// `address.codehash`, deliberately NOT by calling `LibCodeGen.filePrefix` and
/// `LibCodeGen.bytecodeHashConstantString`. Calling those would assert the
/// library agrees with itself and would follow any drift in them silently;
/// consumers have the literal committed in their repos, so the literal is the
/// oracle.
contract LibFsBuildFileForContractTest is Test {
    /// Every test writes under `src/generated/`, which is a committed directory
    /// in this repo. Each test owns a distinct name so parallel suites cannot
    /// collide, none of them is `CodeGennable` (the committed artifact), and
    /// each removes its file again.
    function cleanup(string memory contractName) internal {
        string memory path = LibFs.pathForContract(contractName);
        if (vm.exists(path)) {
            vm.removeFile(path);
        }
    }

    /// The whole file, byte for byte: prefix, then the bytecode hash constant,
    /// then the body, with nothing between them and nothing after.
    function expectedFile(address instance, string memory body) internal view returns (string memory) {
        //REUSE-IgnoreStart
        return string.concat(
            "// SPDX-License-Identifier: LicenseRef-DCL-1.0\n"
            "// SPDX-FileCopyrightText: Copyright (c) 2020 Rain Open Source Software Ltd\n"
            "pragma solidity ^0.8.25;\n\n" "// THIS FILE IS AUTOGENERATED BY THE BUILD SCRIPT. DO NOT EDIT BY HAND.\n"
            "\n" "/// @dev Hash of the known bytecode.\n" "bytes32 constant BYTECODE_HASH = bytes32(",
            vm.toString(instance.codehash),
            ");\n",
            body
        );
        //REUSE-IgnoreEnd
    }

    /// The file that lands on disk is exactly prefix + bytecode hash + body.
    /// This pins the order of the three parts as well as their content: the
    /// pragma has to precede the constant it applies to, and the body is
    /// appended after both.
    function testBuildFileForContractExactContent() external {
        string memory name = "LibFsBuildExact";
        cleanup(name);
        address instance = address(new CodeGennable());
        string memory body = "\n/// @dev Body.\nuint256 constant BODY = 1;\n";

        LibFs.buildFileForContract(vm, instance, name, body);

        assertEq(vm.readFile(LibFs.pathForContract(name)), expectedFile(instance, body));
        cleanup(name);
    }

    /// The file lands at `pathForContract(name)` and only there. Asserted
    /// against the literal path as well, so that the two functions agreeing
    /// with each other is not what makes this pass.
    function testBuildFileForContractWritesToPathForContract() external {
        string memory name = "LibFsBuildPath";
        cleanup(name);
        assertFalse(vm.exists("src/generated/LibFsBuildPath.sol"), "dirty precondition");
        address instance = address(new CodeGennable());

        LibFs.buildFileForContract(vm, instance, name, "\n// body\n");

        assertEq(LibFs.pathForContract(name), "src/generated/LibFsBuildPath.sol", "path disagreement");
        assertTrue(vm.exists("src/generated/LibFsBuildPath.sol"), "not written to the expected path");
        cleanup(name);
    }

    /// First generation for a contract is the normal case: nothing is at the
    /// path yet. Removing a file that is not there reverts, so the existence
    /// check in front of the removal is load bearing and this is what proves
    /// it.
    function testBuildFileForContractFreshPath() external {
        string memory name = "LibFsBuildFresh";
        cleanup(name);
        assertFalse(vm.exists(LibFs.pathForContract(name)), "path is not fresh");
        address instance = address(new CodeGennable());
        string memory body = "\n// fresh\n";

        LibFs.buildFileForContract(vm, instance, name, body);

        assertEq(vm.readFile(LibFs.pathForContract(name)), expectedFile(instance, body));
        cleanup(name);
    }

    /// An existing file at the path is replaced, not appended to and not
    /// partially overwritten. The pre-existing content is deliberately longer
    /// than what is generated, so any tail of it left behind fails here.
    function testBuildFileForContractReplacesExistingContent() external {
        string memory name = "LibFsBuildOverwrite";
        cleanup(name);
        string memory stale = "STALE";
        for (uint256 i = 0; i < 8; i++) {
            stale = string.concat(stale, stale);
        }
        vm.writeFile(LibFs.pathForContract(name), stale);
        assertTrue(bytes(stale).length > 1000, "stale content is not long enough to detect a tail");

        address instance = address(new CodeGennable());
        string memory body = "\n// replaced\n";
        LibFs.buildFileForContract(vm, instance, name, body);

        assertEq(vm.readFile(LibFs.pathForContract(name)), expectedFile(instance, body));
        cleanup(name);
    }

    /// Generation is idempotent: consumers commit the result and CI regenerates
    /// it, so a second run over the same inputs must produce the same bytes.
    function testBuildFileForContractIdempotent() external {
        string memory name = "LibFsBuildIdempotent";
        cleanup(name);
        address instance = address(new CodeGennable());
        string memory body = "\n// idempotent\n";

        LibFs.buildFileForContract(vm, instance, name, body);
        string memory first = vm.readFile(LibFs.pathForContract(name));
        LibFs.buildFileForContract(vm, instance, name, body);
        string memory second = vm.readFile(LibFs.pathForContract(name));

        assertEq(first, second, "second run differs from the first");
        assertEq(second, expectedFile(instance, body));
        cleanup(name);
    }

    /// An empty body still produces the prefix and the bytecode hash constant,
    /// which the docstring says are always included. Nothing is substituted for
    /// the missing body.
    function testBuildFileForContractEmptyBody() external {
        string memory name = "LibFsBuildEmptyBody";
        cleanup(name);
        address instance = address(new CodeGennable());

        LibFs.buildFileForContract(vm, instance, name, "");

        assertEq(vm.readFile(LibFs.pathForContract(name)), expectedFile(instance, ""));
        cleanup(name);
    }

    /// The body is concatenated verbatim with no separator inserted in front of
    /// it. A body that does not begin with a newline therefore continues the
    /// bytecode hash constant's own trailing newline, and the caller owns the
    /// spacing. Quotes and backslashes in the body are not escaped either.
    function testBuildFileForContractBodyVerbatim() external {
        string memory name = "LibFsBuildBodyVerbatim";
        cleanup(name);
        address instance = address(new CodeGennable());
        string memory body = "string constant S = \"a\\\"b\";\n";

        LibFs.buildFileForContract(vm, instance, name, body);

        string memory written = vm.readFile(LibFs.pathForContract(name));
        assertEq(written, expectedFile(instance, body));
        assertTrue(vm.contains(written, "DO NOT EDIT BY HAND.\n\n/// @dev Hash"), "prefix and hash are separated");
        assertTrue(vm.contains(written, ");\nstring constant S ="), "a separator was inserted before the body");
        cleanup(name);
    }

    /// Generating one contract must not disturb another contract's generated
    /// file. Consumers generate many files into the same directory.
    function testBuildFileForContractLeavesSiblingsAlone() external {
        string memory nameA = "LibFsBuildSiblingA";
        string memory nameB = "LibFsBuildSiblingB";
        cleanup(nameA);
        cleanup(nameB);
        address instance = address(new CodeGennable());
        string memory bodyA = "\n// sibling a\n";
        string memory bodyB = "\n// sibling b\n";

        LibFs.buildFileForContract(vm, instance, nameA, bodyA);
        LibFs.buildFileForContract(vm, instance, nameB, bodyB);

        assertEq(vm.readFile(LibFs.pathForContract(nameA)), expectedFile(instance, bodyA), "sibling a was disturbed");
        assertEq(vm.readFile(LibFs.pathForContract(nameB)), expectedFile(instance, bodyB), "sibling b is wrong");
        cleanup(nameA);
        cleanup(nameB);
    }

    /// The bytecode hash is read from the instance that was passed in, not from
    /// the caller and not from a fixed address. Two addresses holding different
    /// code produce different files.
    function testBuildFileForContractUsesTheGivenInstance() external {
        string memory name = "LibFsBuildInstance";
        cleanup(name);
        address instance = address(new CodeGennable());
        address other = address(this);
        assertTrue(instance.code.length > 0 && other.code.length > 0, "both addresses must hold code");
        assertNotEq(instance.codehash, other.codehash, "addresses must hold different code");

        LibFs.buildFileForContract(vm, instance, name, "");
        string memory fromInstance = vm.readFile(LibFs.pathForContract(name));
        LibFs.buildFileForContract(vm, other, name, "");
        string memory fromOther = vm.readFile(LibFs.pathForContract(name));

        assertNotEq(fromInstance, fromOther, "instance is not what the hash is read from");
        assertEq(fromInstance, expectedFile(instance, ""));
        assertEq(fromOther, expectedFile(other, ""));
        cleanup(name);
    }
}
