// SPDX-License-Identifier: LicenseRef-DCL-1.0
// SPDX-FileCopyrightText: Copyright (c) 2020 Rain Open Source Software Ltd
pragma solidity =0.8.25;

import {Test} from "forge-std-1.16.1/src/Test.sol";
import {LibFs} from "src/lib/LibFs.sol";
import {LibCodeGen, InvalidContractName, CodelessInstance} from "src/lib/LibCodeGen.sol";
import {CodeGennable} from "test/concrete/CodeGennable.sol";
import {LibFsExternal} from "test/concrete/LibFsExternal.sol";
import {LibCodeGenSlow} from "test/lib/LibCodeGenSlow.sol";

/// @title LibFsBuildFileForContractTest
/// @notice `buildFileForContract` is the only thing in this repo that touches
/// disk. What it writes is Solidity source that a consumer commits and imports,
/// so these assert the exact bytes of the file on disk, at the exact path, for
/// the whole file rather than for a fragment of it.
///
/// The expected content is rebuilt here from the literal text and from
/// `address.codehash`, deliberately NOT by calling `LibCodeGen.filePrefix` and
/// `LibCodeGen.bytecodeHashConstantString`. Calling those would assert the
/// library agrees with itself and would follow any drift in them silently;
/// consumers have the literal committed in their repos, so the literal is the
/// oracle.
contract LibFsBuildFileForContractTest is Test {
    /// `vm.expectRevert` needs a call frame, and `buildFileForContract` is an
    /// internal library function that is inlined into its caller.
    LibFsExternal internal immutable iExternal;

    constructor() {
        iExternal = new LibFsExternal();
    }

    /// Every test writes under `src/generated/`, which is a committed directory
    /// in this repo. Each test owns a distinct name so parallel suites cannot
    /// collide, none of them is `CodeGennable` (the committed artifact), and
    /// each removes its file again.
    function cleanup(string memory contractName) internal {
        string memory path = LibFs.pathForContract(contractName);
        if (vm.exists(path)) {
            vm.removeFile(path);
        }
    }

    /// The whole file, byte for byte: prefix, then the bytecode hash constant,
    /// then the body, with nothing between them and nothing after.
    function expectedFile(address instance, string memory body) internal view returns (string memory) {
        //REUSE-IgnoreStart
        return string.concat(
            "// SPDX-License-Identifier: LicenseRef-DCL-1.0\n"
            "// SPDX-FileCopyrightText: Copyright (c) 2020 Rain Open Source Software Ltd\n"
            "pragma solidity ^0.8.25;\n\n" "// THIS FILE IS AUTOGENERATED BY THE BUILD SCRIPT. DO NOT EDIT BY HAND.\n"
            "\n" "/// @dev Hash of the known bytecode.\n" "bytes32 constant BYTECODE_HASH = bytes32(",
            vm.toString(instance.codehash),
            ");\n",
            body
        );
        //REUSE-IgnoreEnd
    }

    /// The file that lands on disk is exactly prefix + bytecode hash + body.
    /// This pins the order of the three parts as well as their content: the
    /// pragma has to precede the constant it applies to, and the body is
    /// appended after both.
    function testBuildFileForContractExactContent() external {
        string memory name = "LibFsBuildExact";
        cleanup(name);
        address instance = address(new CodeGennable());
        string memory body = "\n/// @dev Body.\nuint256 constant BODY = 1;\n";

        LibFs.buildFileForContract(vm, instance, name, body);

        assertEq(vm.readFile(LibFs.pathForContract(name)), expectedFile(instance, body));
        cleanup(name);
    }

    /// The file lands at `pathForContract(name)` and only there. Asserted
    /// against the literal path as well, so that the two functions agreeing
    /// with each other is not what makes this pass.
    function testBuildFileForContractWritesToPathForContract() external {
        string memory name = "LibFsBuildPath";
        cleanup(name);
        assertFalse(vm.exists("src/generated/LibFsBuildPath.sol"), "dirty precondition");
        address instance = address(new CodeGennable());

        LibFs.buildFileForContract(vm, instance, name, "\n// body\n");

        assertEq(LibFs.pathForContract(name), "src/generated/LibFsBuildPath.sol", "path disagreement");
        assertTrue(vm.exists("src/generated/LibFsBuildPath.sol"), "not written to the expected path");
        cleanup(name);
    }

    /// First generation for a contract is the normal case: nothing is at the
    /// path yet. Removing a file that is not there reverts, so the existence
    /// check in front of the removal is load bearing and this is what proves
    /// it.
    function testBuildFileForContractFreshPath() external {
        string memory name = "LibFsBuildFresh";
        cleanup(name);
        assertFalse(vm.exists(LibFs.pathForContract(name)), "path is not fresh");
        address instance = address(new CodeGennable());
        string memory body = "\n// fresh\n";

        LibFs.buildFileForContract(vm, instance, name, body);

        assertEq(vm.readFile(LibFs.pathForContract(name)), expectedFile(instance, body));
        cleanup(name);
    }

    /// An existing file at the path is replaced, not appended to and not
    /// partially overwritten. The pre-existing content is deliberately longer
    /// than what is generated, so any tail of it left behind fails here.
    function testBuildFileForContractReplacesExistingContent() external {
        string memory name = "LibFsBuildOverwrite";
        cleanup(name);
        string memory stale = "STALE";
        for (uint256 i = 0; i < 8; i++) {
            stale = string.concat(stale, stale);
        }
        vm.writeFile(LibFs.pathForContract(name), stale);
        assertTrue(bytes(stale).length > 1000, "stale content is not long enough to detect a tail");

        address instance = address(new CodeGennable());
        string memory body = "\n// replaced\n";
        LibFs.buildFileForContract(vm, instance, name, body);

        assertEq(vm.readFile(LibFs.pathForContract(name)), expectedFile(instance, body));
        cleanup(name);
    }

    /// Generation is idempotent: consumers commit the result and CI regenerates
    /// it, so a second run over the same inputs must produce the same bytes.
    function testBuildFileForContractIdempotent() external {
        string memory name = "LibFsBuildIdempotent";
        cleanup(name);
        address instance = address(new CodeGennable());
        string memory body = "\n// idempotent\n";

        LibFs.buildFileForContract(vm, instance, name, body);
        string memory first = vm.readFile(LibFs.pathForContract(name));
        LibFs.buildFileForContract(vm, instance, name, body);
        string memory second = vm.readFile(LibFs.pathForContract(name));

        assertEq(first, second, "second run differs from the first");
        assertEq(second, expectedFile(instance, body));
        cleanup(name);
    }

    /// An empty body still produces the prefix and the bytecode hash constant,
    /// which the docstring says are always included. Nothing is substituted for
    /// the missing body.
    function testBuildFileForContractEmptyBody() external {
        string memory name = "LibFsBuildEmptyBody";
        cleanup(name);
        address instance = address(new CodeGennable());

        LibFs.buildFileForContract(vm, instance, name, "");

        assertEq(vm.readFile(LibFs.pathForContract(name)), expectedFile(instance, ""));
        cleanup(name);
    }

    /// The body is concatenated verbatim with no separator inserted in front of
    /// it. A body that does not begin with a newline therefore continues the
    /// bytecode hash constant's own trailing newline, and the caller owns the
    /// spacing. Quotes and backslashes in the body are not escaped either.
    function testBuildFileForContractBodyVerbatim() external {
        string memory name = "LibFsBuildBodyVerbatim";
        cleanup(name);
        address instance = address(new CodeGennable());
        string memory body = "string constant S = \"a\\\"b\";\n";

        LibFs.buildFileForContract(vm, instance, name, body);

        string memory written = vm.readFile(LibFs.pathForContract(name));
        assertEq(written, expectedFile(instance, body));
        assertTrue(vm.contains(written, "DO NOT EDIT BY HAND.\n\n/// @dev Hash"), "prefix and hash are separated");
        assertTrue(vm.contains(written, ");\nstring constant S ="), "a separator was inserted before the body");
        cleanup(name);
    }

    /// Generating one contract must not disturb another contract's generated
    /// file. Consumers generate many files into the same directory.
    function testBuildFileForContractLeavesSiblingsAlone() external {
        string memory nameA = "LibFsBuildSiblingA";
        string memory nameB = "LibFsBuildSiblingB";
        cleanup(nameA);
        cleanup(nameB);
        address instance = address(new CodeGennable());
        string memory bodyA = "\n// sibling a\n";
        string memory bodyB = "\n// sibling b\n";

        LibFs.buildFileForContract(vm, instance, nameA, bodyA);
        LibFs.buildFileForContract(vm, instance, nameB, bodyB);

        assertEq(vm.readFile(LibFs.pathForContract(nameA)), expectedFile(instance, bodyA), "sibling a was disturbed");
        assertEq(vm.readFile(LibFs.pathForContract(nameB)), expectedFile(instance, bodyB), "sibling b is wrong");
        cleanup(nameA);
        cleanup(nameB);
    }

    /// `src/generated/CodeGennable.sol` is committed, and `script/Build.sol`
    /// builds it through this function. Nothing in `forge test` noticed when it
    /// went stale — only the separate `rainix-copy-artifacts` job did, by
    /// regenerating and diffing. This asserts the committed file still opens
    /// with what `buildFileForContract` writes today, so drift between the
    /// library and the artifact it produced reds the suite too.
    ///
    /// Deliberately built from `LibCodeGen` here, unlike the tests above: the
    /// claim is that the committed bytes match what the library emits now, so
    /// the library is the correct side to read it from and the file on disk is
    /// the oracle.
    function testBuildFileForContractCommittedArtifactIsCurrent() external {
        address instance = address(new CodeGennable());
        string memory header =
            string.concat(LibCodeGen.filePrefix(), LibCodeGen.bytecodeHashConstantString(vm, instance));
        bytes memory committed = bytes(vm.readFile(LibFs.pathForContract("CodeGennable")));

        assertTrue(committed.length >= bytes(header).length, "committed artifact is shorter than the header");
        bytes memory actual = new bytes(bytes(header).length);
        for (uint256 i = 0; i < actual.length; i++) {
            actual[i] = committed[i];
        }
        assertEq(actual, bytes(header), "committed artifact is stale, regenerate with script/Build.sol");
    }

    /// The bytecode hash is read from the instance that was passed in, not from
    /// the caller and not from a fixed address. Two addresses holding different
    /// code produce different files.
    function testBuildFileForContractUsesTheGivenInstance() external {
        string memory name = "LibFsBuildInstance";
        cleanup(name);
        address instance = address(new CodeGennable());
        address other = address(this);
        assertTrue(instance.code.length > 0 && other.code.length > 0, "both addresses must hold code");
        assertNotEq(instance.codehash, other.codehash, "addresses must hold different code");

        LibFs.buildFileForContract(vm, instance, name, "");
        string memory fromInstance = vm.readFile(LibFs.pathForContract(name));
        LibFs.buildFileForContract(vm, other, name, "");
        string memory fromOther = vm.readFile(LibFs.pathForContract(name));

        assertNotEq(fromInstance, fromOther, "instance is not what the hash is read from");
        assertEq(fromInstance, expectedFile(instance, ""));
        assertEq(fromOther, expectedFile(other, ""));
        cleanup(name);
    }

    /// Generating the content can revert: a codeless instance has no bytecode
    /// hash to name. The content is built before anything on disk is touched,
    /// so a build that fails leaves the file it was about to replace exactly as
    /// it found it. Cheatcode filesystem effects are not rolled back by the
    /// revert, so an unlink that ran ahead of the failure would be permanent
    /// and the visible symptom would be a missing generated artifact rather
    /// than the `CodelessInstance` that caused it.
    function testBuildFileForContractFailedBuildKeepsExistingFile() external {
        string memory name = "LibFsBuildFailedKeeps";
        address codeless = address(uint160(0xdead));
        assertEq(codeless.code.length, 0, "instance must hold no code");
        string memory path = LibFs.pathForContract(name);
        cleanup(name);
        vm.writeFile(path, "PRE-EXISTING");

        vm.expectRevert(abi.encodeWithSelector(CodelessInstance.selector, codeless));
        iExternal.buildFileForContract(vm, codeless, name, "\n// body\n");

        assertTrue(vm.exists(path), "a failed build destroyed the existing file");
        assertEq(vm.readFile(path), "PRE-EXISTING", "a failed build rewrote the existing file");
        cleanup(name);
    }

    /// Removes whatever is at `path`, so that a test asserting nothing was
    /// written there establishes its own precondition rather than assuming one.
    function cleanupPath(string memory path) internal {
        if (vm.exists(path)) {
            if (vm.isDir(path)) {
                vm.removeDir(path, true);
            } else {
                vm.removeFile(path);
            }
        }
    }

    /// A name that is not a Solidity identifier gets no path from
    /// `pathForContract`, and `buildFileForContract` asks for the path before it
    /// reaches a cheatcode, so the refusal arrives before anything is written.
    /// That the path is refused at all is asserted in `LibFsTest`; what is
    /// asserted here is that the write inherits it, and that nothing lands on
    /// disk when it does.
    function assertNameRejected(string memory contractName) internal {
        vm.expectRevert(abi.encodeWithSelector(InvalidContractName.selector, contractName));
        iExternal.buildFileForContract(vm, address(this), contractName, "");
    }

    /// The path for an empty name is `src/generated/.sol`: valid generated
    /// Solidity at a path that no compiler picks up as a contract file and that
    /// `ls` hides, written by a build that reports success. Refused, and no
    /// file appears there.
    function testBuildFileForContractRejectsEmptyName() external {
        cleanupPath("src/generated/.sol");
        assertFalse(vm.exists("src/generated/.sol"), "dirty precondition");
        assertNameRejected("");
        assertFalse(vm.exists("src/generated/.sol"), "an empty name still wrote a file");
    }

    /// A separator in the name puts the file in a subdirectory of the generated
    /// directory, which the `read-write` grant on that directory admits, so the
    /// refusal has to come from the library.
    function testBuildFileForContractRejectsSubdirectoryName() external {
        cleanupPath("src/generated/sub");
        assertFalse(vm.exists("src/generated/sub"), "dirty precondition");
        assertNameRejected("sub/LibFsBuildSub");
        assertFalse(vm.exists("src/generated/sub"), "a separator still created a subdirectory");
    }

    /// A relative directory reference leaves the generated directory. Under this
    /// repo's `fs_permissions` the write is refused anyway, but under the
    /// `read-write` grant on `.` that consumers commonly write it is not, so the
    /// refusal has to come from here.
    function testBuildFileForContractRejectsTraversalName() external {
        assertNameRejected("..");
        assertNameRejected("../../ESCAPED");
    }

    /// The `.sol` extension is appended by the library, so a name that carries
    /// one would produce `Foo.sol.sol`.
    function testBuildFileForContractRejectsExtensionInName() external {
        assertNameRejected("LibFsBuildExtension.sol");
    }

    /// Every name that is not a Solidity identifier is refused, not just the
    /// ones named above.
    function testBuildFileForContractRejectsEveryNonIdentifierName(bytes memory nameBytes) external {
        string memory contractName = string(nameBytes);
        vm.assume(!LibCodeGenSlow.isContractNameSlow(contractName));
        assertNameRejected(contractName);
    }
}
