// SPDX-License-Identifier: LicenseRef-DCL-1.0
// SPDX-FileCopyrightText: Copyright (c) 2020 Rain Open Source Software Ltd
pragma solidity =0.8.25;

import {Test} from "forge-std-1.16.2/src/Test.sol";
import {LibCodeGen, InvalidSpdxLicenseIdentifier, InvalidCopyrightText} from "src/lib/LibCodeGen.sol";

// The subject of this whole file is emitted licence text, so SPDX tag prefixes
// appear throughout it without a value attached. The file's own header is above
// this line and still registers.
//REUSE-IgnoreStart

/// @title LibCodeGenFilePrefixTest
/// @notice The prefix heads every file that is generated through this library,
/// in every consumer repo in every org. The licence and the copyright holder it
/// states belong to the repo the file lands in, so what is asserted here is that
/// the caller's values reach the header verbatim and that nothing this repo
/// believes about its own licensing survives into a file it does not own.
contract LibCodeGenFilePrefixTest is Test {
    /// Reachable only through an external call so that a revert can be caught
    /// rather than aborting the test.
    function callFilePrefix(string memory spdxLicenseIdentifier, string memory copyrightText)
        external
        pure
        returns (string memory)
    {
        return LibCodeGen.filePrefix(spdxLicenseIdentifier, copyrightText);
    }

    /// Printable ASCII of at least one character, drawn from a seed. Fuzzing a
    /// string directly cannot reach the accepted half of the domain in a form
    /// the string cheatcodes can read back, because arbitrary bytes are not
    /// valid UTF-8.
    function textFromSeed(bytes memory seed) internal pure returns (string memory) {
        bytes memory text = new bytes(seed.length + 1);
        text[0] = "X";
        for (uint256 i = 0; i < seed.length; i++) {
            text[i + 1] = bytes1(0x20 + (uint8(seed[i]) % 95));
        }
        return string(text);
    }

    /// The prefix heads every generated file in every consumer repo, so a
    /// change to the part of it this library owns rewrites committed files org
    /// wide. Pinned exactly, with this repo's own licence and copyright as the
    /// caller's values, so that lands as a deliberate, reviewable diff rather
    /// than a surprise on the next regeneration.
    ///
    /// The pinned text names no script. Each consumer names its own build
    /// script, so a script path in the prefix would be a claim this library
    /// cannot keep. Exactly one string passes here, so every string that
    /// names a `.sol` file fails, and pinning the whole prefix is what
    /// refuses them.
    function testFilePrefixExact() external pure {
        assertEq(
            LibCodeGen.filePrefix("LicenseRef-DCL-1.0", "Copyright (c) 2020 Rain Open Source Software Ltd"),
            "// SPDX-License-Identifier: LicenseRef-DCL-1.0\n"
            "// SPDX-FileCopyrightText: Copyright (c) 2020 Rain Open Source Software Ltd\n"
            "pragma solidity ^0.8.25;\n\n" "// THIS FILE IS AUTOGENERATED BY THE BUILD SCRIPT. DO NOT EDIT BY HAND.\n"
        );
    }

    /// A consumer in another org gets its own licence and its own copyright
    /// holder, and none of this repo's. `S01-Issuer/st0x.deploy` generates
    /// through this library into append-only deploy-pin snapshots, so what those
    /// files claim about their licensing is permanent once written.
    function testFilePrefixCarriesTheCallersLicenceAndCopyright() external pure {
        string memory prefix = LibCodeGen.filePrefix("MIT", "Copyright (c) 2026 S01 Issuer GmbH");
        assertEq(
            prefix,
            "// SPDX-License-Identifier: MIT\n" "// SPDX-FileCopyrightText: Copyright (c) 2026 S01 Issuer GmbH\n"
            "pragma solidity ^0.8.25;\n\n" "// THIS FILE IS AUTOGENERATED BY THE BUILD SCRIPT. DO NOT EDIT BY HAND.\n"
        );
        assertFalse(vm.contains(prefix, "LicenseRef-DCL-1.0"), "this repo's licence reached another repo's file");
        assertFalse(
            vm.contains(prefix, "Rain Open Source Software Ltd"),
            "this repo's copyright holder reached another repo's file"
        );
    }

    /// Over arbitrary accepted values, the first two lines of the prefix are the
    /// two SPDX tags carrying the caller's values verbatim, and the three lines
    /// after them are fixed. Read by splitting the emitted prefix on newlines
    /// rather than by rebuilding it with the concatenation the library itself
    /// uses, so a change to either tag, to the order of the two lines, or to the
    /// number of lines fails here.
    function testFilePrefixLinesAreTheCallersValues(bytes memory licenceSeed, bytes memory copyrightSeed)
        external
        view
    {
        string memory spdxLicenseIdentifier = textFromSeed(licenceSeed);
        string memory copyrightText = textFromSeed(copyrightSeed);

        string[] memory lines = vm.split(this.callFilePrefix(spdxLicenseIdentifier, copyrightText), "\n");

        assertEq(lines.length, 6, "prefix is not five lines and a trailing newline");
        assertEq(lines[0], string.concat("// SPDX-License-Identifier: ", spdxLicenseIdentifier));
        assertEq(lines[1], string.concat("// SPDX-FileCopyrightText: ", copyrightText));
        assertEq(lines[2], "pragma solidity ^0.8.25;");
        assertEq(lines[3], "");
        assertEq(lines[4], "// THIS FILE IS AUTOGENERATED BY THE BUILD SCRIPT. DO NOT EDIT BY HAND.");
        assertEq(lines[5], "");
    }

    /// An empty licence identifier emits the licence tag with nothing after it.
    /// A REUSE lint that tests for the tag's presence passes that file, so the
    /// file would report as licensed while naming no licence, and solc refuses
    /// it with "Invalid SPDX license identifier" so the repo it is generated
    /// into stops compiling.
    function testFilePrefixRejectsEmptyLicence() external {
        vm.expectRevert(abi.encodeWithSelector(InvalidSpdxLicenseIdentifier.selector, ""));
        this.callFilePrefix("", "Copyright (c) 2020 Rain Open Source Software Ltd");
    }

    /// An empty copyright text names no holder, for the same reason.
    function testFilePrefixRejectsEmptyCopyright() external {
        vm.expectRevert(abi.encodeWithSelector(InvalidCopyrightText.selector, ""));
        this.callFilePrefix("LicenseRef-DCL-1.0", "");
    }

    /// A line break ends the header line the value is interpolated into, so the
    /// remainder lands as source rather than as part of the tag. A value chosen
    /// to do it deliberately writes a second, contradicting SPDX tag that a
    /// presence check accepts. Carriage return counts: Solidity ends a `//`
    /// comment at either.
    function testFilePrefixRejectsLineBreakInLicence() external {
        vm.expectRevert(
            abi.encodeWithSelector(
                InvalidSpdxLicenseIdentifier.selector, "MIT\n// SPDX-License-Identifier: GPL-3.0-only"
            )
        );
        this.callFilePrefix("MIT\n// SPDX-License-Identifier: GPL-3.0-only", "Copyright (c) 2026 Someone");

        vm.expectRevert(abi.encodeWithSelector(InvalidSpdxLicenseIdentifier.selector, "MIT\r"));
        this.callFilePrefix("MIT\r", "Copyright (c) 2026 Someone");
    }

    /// The copyright text is interpolated into its own header line and carries
    /// the same rule.
    function testFilePrefixRejectsLineBreakInCopyright() external {
        vm.expectRevert(
            abi.encodeWithSelector(
                InvalidCopyrightText.selector, "Copyright (c) 2026 Someone\n// SPDX-FileCopyrightText: Someone Else"
            )
        );
        this.callFilePrefix("MIT", "Copyright (c) 2026 Someone\n// SPDX-FileCopyrightText: Someone Else");

        vm.expectRevert(abi.encodeWithSelector(InvalidCopyrightText.selector, "Copyright (c) 2026 Someone\r"));
        this.callFilePrefix("MIT", "Copyright (c) 2026 Someone\r");
    }

    /// A line break anywhere in the value is refused, not only one at the end or
    /// one at a boundary. Fuzzed over the position and over the surrounding
    /// text, so a check that looked at the first or the last byte only would
    /// fail here.
    function testFilePrefixRejectsLineBreakAtAnyPosition(bytes memory seed, uint256 position, bool carriageReturn)
        external
    {
        bytes memory licenceBytes = bytes(textFromSeed(seed));
        licenceBytes[position % licenceBytes.length] = carriageReturn ? bytes1(0x0D) : bytes1(0x0A);
        string memory spdxLicenseIdentifier = string(licenceBytes);

        vm.expectRevert(abi.encodeWithSelector(InvalidSpdxLicenseIdentifier.selector, spdxLicenseIdentifier));
        this.callFilePrefix(spdxLicenseIdentifier, "Copyright (c) 2026 Someone");

        bytes memory copyrightBytes = bytes(textFromSeed(seed));
        copyrightBytes[position % copyrightBytes.length] = carriageReturn ? bytes1(0x0D) : bytes1(0x0A);
        string memory copyrightText = string(copyrightBytes);

        vm.expectRevert(abi.encodeWithSelector(InvalidCopyrightText.selector, copyrightText));
        this.callFilePrefix("MIT", copyrightText);
    }

    /// Acceptance is decided by the line break rule and by nothing else: a value
    /// made only of printable ASCII is not refused. The claim is that the call
    /// does not revert; what the header holds for an accepted value is pinned by
    /// `testFilePrefixLinesAreTheCallersValues` over the same domain.
    function testFilePrefixAcceptsEveryNonLineBreakValue(bytes memory seed) external view {
        string memory text = textFromSeed(seed);
        this.callFilePrefix(text, text);
    }

    /// The licence is checked before the copyright, so a call that gets both
    /// wrong reverts on the licence rather than on whichever the compiler
    /// happened to evaluate first.
    function testFilePrefixChecksLicenceFirst() external {
        vm.expectRevert(abi.encodeWithSelector(InvalidSpdxLicenseIdentifier.selector, ""));
        this.callFilePrefix("", "");
    }
}
//REUSE-IgnoreEnd
