// SPDX-License-Identifier: LicenseRef-DCL-1.0
// SPDX-FileCopyrightText: Copyright (c) 2020 Rain Open Source Software Ltd
pragma solidity =0.8.25;

import {Test} from "forge-std-1.16.1/src/Test.sol";
import {LibCodeGen} from "src/lib/LibCodeGen.sol";

/// @title LibCodeGenFilePrefixTest
contract LibCodeGenFilePrefixTest is Test {
    /// The prefix heads every generated file in every consumer repo, so a
    /// change here rewrites committed files org wide. Pinned exactly so that
    /// lands as a deliberate, reviewable diff rather than a surprise on the
    /// next regeneration.
    ///
    /// The pinned text names no script. Each consumer names its own build
    /// script, so a script path in the prefix would be a claim this library
    /// cannot keep. Exactly one string passes here, so every string that
    /// names a `.sol` file fails, and pinning the whole prefix is what
    /// refuses them.
    function testFilePrefixExact() external pure {
        //REUSE-IgnoreStart
        assertEq(
            LibCodeGen.filePrefix(),
            "// SPDX-License-Identifier: LicenseRef-DCL-1.0\n"
            "// SPDX-FileCopyrightText: Copyright (c) 2020 Rain Open Source Software Ltd\n"
            "pragma solidity ^0.8.25;\n\n" "// THIS FILE IS AUTOGENERATED BY THE BUILD SCRIPT. DO NOT EDIT BY HAND.\n"
        );
        //REUSE-IgnoreEnd
    }
}
