// SPDX-License-Identifier: LicenseRef-DCL-1.0
// SPDX-FileCopyrightText: Copyright (c) 2020 Rain Open Source Software Ltd
pragma solidity =0.8.25;

import {Test} from "forge-std-1.16.1/src/Test.sol";
import {LibFs, GENERATED_DIR} from "src/lib/LibFs.sol";
import {InvalidContractName, InvalidSpdxLicenseIdentifier, InvalidCopyrightText} from "src/lib/LibCodeGen.sol";
import {CodeGennable} from "test/concrete/CodeGennable.sol";
import {LibFsExternal} from "test/concrete/LibFsExternal.sol";
import {LibCodeGenSlow} from "test/lib/LibCodeGenSlow.sol";

/// @dev The licence identifier this repo declares for its own source. Which
/// values a caller passes is incidental to every test here except
/// `testBuildFileForContractCarriesTheCallersLicenceAndCopyright`, which passes
/// another org's, so these are this repo's own rather than invented.
string constant SPDX_LICENSE_IDENTIFIER = "LicenseRef-DCL-1.0";

/// @dev The copyright text this repo declares for its own source, for the same
/// reason.
string constant COPYRIGHT_TEXT = "Copyright (c) 2020 Rain Open Source Software Ltd";

/// @title LibFsBuildFileForContractTest
/// @notice `buildFileForContract` is the only thing in this repo that touches
/// disk. What it writes is Solidity source that a consumer commits and imports,
/// so these assert the exact bytes of the file on disk, at the exact path, for
/// the whole file rather than for a fragment of it.
///
/// The expected content is rebuilt here from the literal text and from
/// `address.codehash`, deliberately NOT by calling `LibCodeGen.filePrefix` and
/// `LibCodeGen.bytecodeHashConstantString`. Calling those would assert the
/// library agrees with itself and would follow any drift in them silently;
/// consumers have the literal committed in their repos, so the literal is the
/// oracle.
contract LibFsBuildFileForContractTest is Test {
    /// `vm.expectRevert` needs a call frame, and `buildFileForContract` is an
    /// internal library function that is inlined into its caller.
    LibFsExternal internal immutable iExternal;

    constructor() {
        iExternal = new LibFsExternal();
    }

    /// `src/generated/` holds no committed file, so nothing in a fresh clone
    /// creates it. `buildFileForContract` creates it for itself, but
    /// `testBuildFileForContractReplacesExistingContent` writes its stale
    /// content there directly first, and a filtered run may be only that test,
    /// so the directory is not something this contract can inherit from a test
    /// that happened to run earlier.
    function setUp() external {
        vm.createDir(GENERATED_DIR, true);
    }

    /// Called by the tests that generate a file. `src/generated/` holds nothing
    /// committed in this repo, so everything that lands there during a run is
    /// this suite's scratch. Each generating test owns a distinct name so
    /// parallel suites cannot collide, and removes its file again. The tests
    /// that assert a name is refused write nothing at all and do not come
    /// through here.
    function cleanup(string memory contractName) internal {
        string memory path = LibFs.pathForContract(contractName);
        if (vm.exists(path)) {
            vm.removeFile(path);
        }
    }

    /// The whole file, byte for byte: prefix, then the bytecode hash constant,
    /// then the body, with nothing between them and nothing after. The licence
    /// and copyright are the caller's, so they are interpolated here the same
    /// way the file under test interpolates them, and the structure around them
    /// is the literal.
    function expectedFile(
        address instance,
        string memory spdxLicenseIdentifier,
        string memory copyrightText,
        string memory body
    ) internal view returns (string memory) {
        //REUSE-IgnoreStart
        return string.concat(
            "// SPDX-License-Identifier: ",
            spdxLicenseIdentifier,
            "\n" "// SPDX-FileCopyrightText: ",
            copyrightText,
            "\n" "pragma solidity ^0.8.25;\n\n"
            "// THIS FILE IS AUTOGENERATED BY THE BUILD SCRIPT. DO NOT EDIT BY HAND.\n" "\n"
            "/// @dev Hash of the known bytecode.\n" "bytes32 constant BYTECODE_HASH = bytes32(",
            vm.toString(instance.codehash),
            ");\n",
            body
        );
        //REUSE-IgnoreEnd
    }

    /// The file that lands on disk is exactly prefix + bytecode hash + body.
    /// This pins the order of the three parts as well as their content: the
    /// pragma has to precede the constant it applies to, and the body is
    /// appended after both.
    function testBuildFileForContractExactContent() external {
        string memory name = "LibFsBuildExact";
        cleanup(name);
        address instance = address(new CodeGennable());
        string memory body = "\n/// @dev Body.\nuint256 constant BODY = 1;\n";

        LibFs.buildFileForContract(vm, instance, name, SPDX_LICENSE_IDENTIFIER, COPYRIGHT_TEXT, body);

        assertEq(
            vm.readFile(LibFs.pathForContract(name)),
            expectedFile(instance, SPDX_LICENSE_IDENTIFIER, COPYRIGHT_TEXT, body)
        );
        cleanup(name);
    }

    /// The file lands at `pathForContract(name)` and only there. Asserted
    /// against the literal path as well, so that the two functions agreeing
    /// with each other is not what makes this pass.
    function testBuildFileForContractWritesToPathForContract() external {
        string memory name = "LibFsBuildPath";
        cleanup(name);
        assertFalse(vm.exists("src/generated/LibFsBuildPath.sol"), "dirty precondition");
        address instance = address(new CodeGennable());

        LibFs.buildFileForContract(vm, instance, name, SPDX_LICENSE_IDENTIFIER, COPYRIGHT_TEXT, "\n// body\n");

        assertEq(LibFs.pathForContract(name), "src/generated/LibFsBuildPath.sol", "path disagreement");
        assertTrue(vm.exists("src/generated/LibFsBuildPath.sol"), "not written to the expected path");
        cleanup(name);
    }

    /// First generation for a contract is the normal case: nothing is at the
    /// path yet. Removing a file that is not there reverts, so the existence
    /// check in front of the removal is load bearing and this is what proves
    /// it.
    function testBuildFileForContractFreshPath() external {
        string memory name = "LibFsBuildFresh";
        cleanup(name);
        assertFalse(vm.exists(LibFs.pathForContract(name)), "path is not fresh");
        address instance = address(new CodeGennable());
        string memory body = "\n// fresh\n";

        LibFs.buildFileForContract(vm, instance, name, SPDX_LICENSE_IDENTIFIER, COPYRIGHT_TEXT, body);

        assertEq(
            vm.readFile(LibFs.pathForContract(name)),
            expectedFile(instance, SPDX_LICENSE_IDENTIFIER, COPYRIGHT_TEXT, body)
        );
        cleanup(name);
    }

    /// An existing file at the path is replaced, not appended to and not
    /// partially overwritten. The pre-existing content is deliberately longer
    /// than what is generated, so any tail of it left behind fails here.
    function testBuildFileForContractReplacesExistingContent() external {
        string memory name = "LibFsBuildOverwrite";
        cleanup(name);
        string memory stale = "STALE";
        for (uint256 i = 0; i < 8; i++) {
            stale = string.concat(stale, stale);
        }
        vm.writeFile(LibFs.pathForContract(name), stale);
        assertTrue(bytes(stale).length > 1000, "stale content is not long enough to detect a tail");

        address instance = address(new CodeGennable());
        string memory body = "\n// replaced\n";
        LibFs.buildFileForContract(vm, instance, name, SPDX_LICENSE_IDENTIFIER, COPYRIGHT_TEXT, body);

        assertEq(
            vm.readFile(LibFs.pathForContract(name)),
            expectedFile(instance, SPDX_LICENSE_IDENTIFIER, COPYRIGHT_TEXT, body)
        );
        cleanup(name);
    }

    /// Generation is idempotent: consumers commit the result and CI regenerates
    /// it, so a second run over the same inputs must produce the same bytes.
    function testBuildFileForContractIdempotent() external {
        string memory name = "LibFsBuildIdempotent";
        cleanup(name);
        address instance = address(new CodeGennable());
        string memory body = "\n// idempotent\n";

        LibFs.buildFileForContract(vm, instance, name, SPDX_LICENSE_IDENTIFIER, COPYRIGHT_TEXT, body);
        string memory first = vm.readFile(LibFs.pathForContract(name));
        LibFs.buildFileForContract(vm, instance, name, SPDX_LICENSE_IDENTIFIER, COPYRIGHT_TEXT, body);
        string memory second = vm.readFile(LibFs.pathForContract(name));

        assertEq(first, second, "second run differs from the first");
        assertEq(second, expectedFile(instance, SPDX_LICENSE_IDENTIFIER, COPYRIGHT_TEXT, body));
        cleanup(name);
    }

    /// An empty body still produces the prefix and the bytecode hash constant,
    /// which the docstring says are always included. Nothing is substituted for
    /// the missing body.
    function testBuildFileForContractEmptyBody() external {
        string memory name = "LibFsBuildEmptyBody";
        cleanup(name);
        address instance = address(new CodeGennable());

        LibFs.buildFileForContract(vm, instance, name, SPDX_LICENSE_IDENTIFIER, COPYRIGHT_TEXT, "");

        assertEq(
            vm.readFile(LibFs.pathForContract(name)),
            expectedFile(instance, SPDX_LICENSE_IDENTIFIER, COPYRIGHT_TEXT, "")
        );
        cleanup(name);
    }

    /// The body is concatenated verbatim with no separator inserted in front of
    /// it. A body that does not begin with a newline therefore continues the
    /// bytecode hash constant's own trailing newline, and the caller owns the
    /// spacing. Quotes and backslashes in the body are not escaped either.
    function testBuildFileForContractBodyVerbatim() external {
        string memory name = "LibFsBuildBodyVerbatim";
        cleanup(name);
        address instance = address(new CodeGennable());
        string memory body = "string constant S = \"a\\\"b\";\n";

        LibFs.buildFileForContract(vm, instance, name, SPDX_LICENSE_IDENTIFIER, COPYRIGHT_TEXT, body);

        string memory written = vm.readFile(LibFs.pathForContract(name));
        assertEq(written, expectedFile(instance, SPDX_LICENSE_IDENTIFIER, COPYRIGHT_TEXT, body));
        assertTrue(vm.contains(written, "DO NOT EDIT BY HAND.\n\n/// @dev Hash"), "prefix and hash are separated");
        assertTrue(vm.contains(written, ");\nstring constant S ="), "a separator was inserted before the body");
        cleanup(name);
    }

    /// Generating one contract must not disturb another contract's generated
    /// file. Consumers generate many files into the same directory.
    function testBuildFileForContractLeavesSiblingsAlone() external {
        string memory nameA = "LibFsBuildSiblingA";
        string memory nameB = "LibFsBuildSiblingB";
        cleanup(nameA);
        cleanup(nameB);
        address instance = address(new CodeGennable());
        string memory bodyA = "\n// sibling a\n";
        string memory bodyB = "\n// sibling b\n";

        LibFs.buildFileForContract(vm, instance, nameA, SPDX_LICENSE_IDENTIFIER, COPYRIGHT_TEXT, bodyA);
        LibFs.buildFileForContract(vm, instance, nameB, SPDX_LICENSE_IDENTIFIER, COPYRIGHT_TEXT, bodyB);

        assertEq(
            vm.readFile(LibFs.pathForContract(nameA)),
            expectedFile(instance, SPDX_LICENSE_IDENTIFIER, COPYRIGHT_TEXT, bodyA),
            "sibling a was disturbed"
        );
        assertEq(
            vm.readFile(LibFs.pathForContract(nameB)),
            expectedFile(instance, SPDX_LICENSE_IDENTIFIER, COPYRIGHT_TEXT, bodyB),
            "sibling b is wrong"
        );
        cleanup(nameA);
        cleanup(nameB);
    }

    /// The bytecode hash is read from the instance that was passed in, not from
    /// the caller and not from a fixed address. Two addresses holding different
    /// code produce different files.
    function testBuildFileForContractUsesTheGivenInstance() external {
        string memory name = "LibFsBuildInstance";
        cleanup(name);
        address instance = address(new CodeGennable());
        address other = address(this);
        assertTrue(instance.code.length > 0 && other.code.length > 0, "both addresses must hold code");
        assertNotEq(instance.codehash, other.codehash, "addresses must hold different code");

        LibFs.buildFileForContract(vm, instance, name, SPDX_LICENSE_IDENTIFIER, COPYRIGHT_TEXT, "");
        string memory fromInstance = vm.readFile(LibFs.pathForContract(name));
        LibFs.buildFileForContract(vm, other, name, SPDX_LICENSE_IDENTIFIER, COPYRIGHT_TEXT, "");
        string memory fromOther = vm.readFile(LibFs.pathForContract(name));

        assertNotEq(fromInstance, fromOther, "instance is not what the hash is read from");
        assertEq(fromInstance, expectedFile(instance, SPDX_LICENSE_IDENTIFIER, COPYRIGHT_TEXT, ""));
        assertEq(fromOther, expectedFile(other, SPDX_LICENSE_IDENTIFIER, COPYRIGHT_TEXT, ""));
        cleanup(name);
    }

    /// The file that lands on disk declares the caller's licence and the
    /// caller's copyright holder, and none of this repo's. Every consumer of
    /// this library commits what it writes, and `S01-Issuer/st0x.deploy` commits
    /// it into append-only deploy-pin snapshots, so a header naming the wrong
    /// holder is permanent in another org's release record.
    ///
    /// The file is read and removed before anything is asserted. A failing
    /// assertion ends the test where it stands, so asserting first would leave
    /// the written file in `src/generated/` for whatever runs next.
    function testBuildFileForContractCarriesTheCallersLicenceAndCopyright() external {
        string memory name = "LibFsBuildForeignLicence";
        cleanup(name);
        address instance = address(new CodeGennable());
        string memory body = "\n// foreign\n";

        LibFs.buildFileForContract(vm, instance, name, "MIT", "Copyright (c) 2026 S01 Issuer GmbH", body);

        string memory written = vm.readFile(LibFs.pathForContract(name));
        cleanup(name);

        assertEq(written, expectedFile(instance, "MIT", "Copyright (c) 2026 S01 Issuer GmbH", body));
        assertFalse(vm.contains(written, "LicenseRef-DCL-1.0"), "this repo's licence reached another repo's file");
        assertFalse(
            vm.contains(written, "Rain Open Source Software Ltd"),
            "this repo's copyright holder reached another repo's file"
        );
    }

    /// The revert data from a write, or empty bytes when the write was
    /// accepted. `vm.expectRevert` would end the test at the call that is
    /// supposed to revert and does not, and a write that reaches disk is not
    /// undone by the revert that follows it, so the file would be left in
    /// `src/generated/` for the next compile to pick up. Catching the revert
    /// keeps the assertion for after the file is removed.
    function headerRejection(
        string memory contractName,
        string memory spdxLicenseIdentifier,
        string memory copyrightText
    ) internal returns (bytes memory) {
        try iExternal.buildFileForContract(vm, address(this), contractName, spdxLicenseIdentifier, copyrightText, "") {
            return "";
        } catch (bytes memory reason) {
            return reason;
        }
    }

    /// The write inherits the rule `filePrefix` puts on the licence and the
    /// copyright, so a build script that names neither cannot produce a file
    /// that claims to be licensed and is not.
    function testBuildFileForContractRejectsInvalidLicenceAndCopyright() external {
        string memory name = "LibFsBuildInvalidHeader";
        cleanup(name);

        bytes memory emptyLicence = headerRejection(name, "", COPYRIGHT_TEXT);
        bytes memory brokenCopyright = headerRejection(name, SPDX_LICENSE_IDENTIFIER, "Copyright (c) 2026 Someone\n");
        bool written = vm.exists(LibFs.pathForContract(name));
        cleanup(name);

        assertEq(
            emptyLicence,
            abi.encodeWithSelector(InvalidSpdxLicenseIdentifier.selector, ""),
            "an empty licence was not refused"
        );
        assertEq(
            brokenCopyright,
            abi.encodeWithSelector(InvalidCopyrightText.selector, "Copyright (c) 2026 Someone\n"),
            "a copyright carrying a line break was not refused"
        );
        assertFalse(written, "a refused header still wrote a file");
    }

    /// Removes whatever is at `path`, so that a test asserting nothing was
    /// written there establishes its own precondition rather than assuming one.
    function cleanupPath(string memory path) internal {
        if (vm.exists(path)) {
            if (vm.isDir(path)) {
                vm.removeDir(path, true);
            } else {
                vm.removeFile(path);
            }
        }
    }

    /// The directory is created when it is not there, so a repo generating for
    /// the first time does not have to commit it. Two levels of it are missing,
    /// so a create that did not also make the missing parent fails here.
    ///
    /// Driven through a directory this test owns rather than through
    /// `GENERATED_DIR` itself. Every generating test in this file writes under
    /// `GENERATED_DIR` and `forge` runs them in parallel, so removing it to
    /// make it missing races all of them. `setUp` above creates `GENERATED_DIR`
    /// for exactly that reason, which is also what makes the library's own
    /// create unreachable from any test that writes there directly.
    function testBuildFileForContractCreatesTheDirectory() external {
        string memory root = string.concat(GENERATED_DIR, "/LibFsBuildCreatesDir");
        string memory dir = string.concat(root, "/nested");
        string memory name = "LibFsBuildCreatesDir";
        cleanupPath(root);
        assertFalse(vm.exists(root), "dirty precondition");
        address instance = address(new CodeGennable());
        string memory body = "\n// created\n";

        LibFs.buildFileForContract(vm, instance, dir, name, SPDX_LICENSE_IDENTIFIER, COPYRIGHT_TEXT, body);

        assertEq(
            vm.readFile(string.concat(dir, "/", name, ".sol")),
            expectedFile(instance, SPDX_LICENSE_IDENTIFIER, COPYRIGHT_TEXT, body)
        );
        cleanupPath(root);
    }

    /// A name that is not a Solidity identifier gets no path from
    /// `pathForContract`, and `buildFileForContract` asks for the path before it
    /// reaches a cheatcode, so the refusal arrives before anything is written.
    /// That the path is refused at all is asserted in `LibFsTest`; what is
    /// asserted here is that the write inherits it, and that nothing lands on
    /// disk when it does.
    function assertNameRejected(string memory contractName) internal {
        vm.expectRevert(abi.encodeWithSelector(InvalidContractName.selector, contractName));
        iExternal.buildFileForContract(vm, address(this), contractName, SPDX_LICENSE_IDENTIFIER, COPYRIGHT_TEXT, "");
    }

    /// The path for an empty name is `src/generated/.sol`: valid generated
    /// Solidity at a path that no compiler picks up as a contract file and that
    /// `ls` hides, written by a build that reports success. Refused, and no
    /// file appears there.
    function testBuildFileForContractRejectsEmptyName() external {
        cleanupPath("src/generated/.sol");
        assertFalse(vm.exists("src/generated/.sol"), "dirty precondition");
        assertNameRejected("");
        assertFalse(vm.exists("src/generated/.sol"), "an empty name still wrote a file");
    }

    /// A separator in the name puts the file in a subdirectory of the generated
    /// directory, which the `read-write` grant on that directory admits, so the
    /// refusal has to come from the library.
    function testBuildFileForContractRejectsSubdirectoryName() external {
        cleanupPath("src/generated/sub");
        assertFalse(vm.exists("src/generated/sub"), "dirty precondition");
        assertNameRejected("sub/LibFsBuildSub");
        assertFalse(vm.exists("src/generated/sub"), "a separator still created a subdirectory");
    }

    /// A relative directory reference leaves the generated directory. Under this
    /// repo's `fs_permissions` the write is refused anyway, but under the
    /// `read-write` grant on `.` that consumers commonly write it is not, so the
    /// refusal has to come from here.
    function testBuildFileForContractRejectsTraversalName() external {
        assertNameRejected("..");
        assertNameRejected("../../ESCAPED");
    }

    /// The `.sol` extension is appended by the library, so a name that carries
    /// one would produce `Foo.sol.sol`.
    function testBuildFileForContractRejectsExtensionInName() external {
        assertNameRejected("LibFsBuildExtension.sol");
    }

    /// Every name that is not a Solidity identifier is refused, not just the
    /// ones named above.
    function testBuildFileForContractRejectsEveryNonIdentifierName(bytes memory nameBytes) external {
        string memory contractName = string(nameBytes);
        vm.assume(!LibCodeGenSlow.isContractNameSlow(contractName));
        assertNameRejected(contractName);
    }
}
