// SPDX-License-Identifier: LicenseRef-DCL-1.0
// SPDX-FileCopyrightText: Copyright (c) 2020 Rain Open Source Software Ltd
pragma solidity =0.8.25;

import {Test} from "forge-std-1.16.1/src/Test.sol";
import {LibFs, InvalidTag} from "src/lib/LibFs.sol";
import {InvalidContractName} from "src/lib/LibCodeGen.sol";
import {CodeGennable} from "test/concrete/CodeGennable.sol";
import {LibFsExternal} from "test/concrete/LibFsExternal.sol";
import {LibCodeGenSlow} from "test/lib/LibCodeGenSlow.sol";

/// @title LibFsBuildFileForTaggedContractTest
/// @notice `buildFileForTaggedContract` writes the per tag deploy pin snapshots
/// the org's release convention freezes. What it writes is Solidity source that
/// a consumer commits, imports and pins deployed addresses against, so these
/// assert the exact bytes of the file on disk, at the exact path, for the whole
/// file rather than for a fragment of it.
///
/// The expected content is rebuilt here from the literal text and from
/// `address.codehash`, deliberately NOT by calling `LibCodeGen.filePrefix` and
/// `LibCodeGen.bytecodeHashConstantString`. Calling those would assert the
/// library agrees with itself and would follow any drift in them silently;
/// consumers have the literal committed in their repos, so the literal is the
/// oracle.
contract LibFsBuildFileForTaggedContractTest is Test {
    /// `vm.expectRevert` needs a call frame, and `buildFileForTaggedContract` is
    /// an internal library function that is inlined into its caller.
    LibFsExternal internal immutable iExternal;

    constructor() {
        iExternal = new LibFsExternal();
    }

    /// Every test writes under `src/generated/`, which is a committed directory
    /// in this repo. Each test owns a distinct tag so parallel suites cannot
    /// collide, none of the tags is one this repo commits, and each removes the
    /// directory it created.
    function cleanup(string memory tag) internal {
        string memory dir = LibFs.dirForTag(tag);
        if (vm.exists(dir)) {
            vm.removeDir(dir, true);
        }
    }

    /// The whole file, byte for byte: prefix, then the bytecode hash constant,
    /// then the body, with nothing between them and nothing after.
    function expectedFile(address instance, string memory body) internal view returns (string memory) {
        //REUSE-IgnoreStart
        return string.concat(
            "// SPDX-License-Identifier: LicenseRef-DCL-1.0\n"
            "// SPDX-FileCopyrightText: Copyright (c) 2020 Rain Open Source Software Ltd\n"
            "pragma solidity ^0.8.25;\n\n" "// THIS FILE IS AUTOGENERATED BY THE BUILD SCRIPT. DO NOT EDIT BY HAND.\n"
            "\n" "/// @dev Hash of the known bytecode.\n" "bytes32 constant BYTECODE_HASH = bytes32(",
            vm.toString(instance.codehash),
            ");\n",
            body
        );
        //REUSE-IgnoreEnd
    }

    /// The file that lands on disk is exactly prefix + bytecode hash + body,
    /// which is byte for byte what the untagged write produces. A snapshot is
    /// the same generated file in a different directory, not a different format.
    function testBuildFileForTaggedContractExactContent() external {
        string memory tag = "0_1_1$taggedExact";
        cleanup(tag);
        address instance = address(new CodeGennable());
        string memory body = "\n/// @dev Body.\nuint256 constant BODY = 1;\n";

        LibFs.buildFileForTaggedContract(vm, instance, tag, "LibFsTaggedExact", body);

        assertEq(vm.readFile(LibFs.pathForTaggedContract(tag, "LibFsTaggedExact")), expectedFile(instance, body));
        cleanup(tag);
    }

    /// The file lands at `pathForTaggedContract(tag, name)` and only there.
    /// Asserted against the literal path as well, so that the two functions
    /// agreeing with each other is not what makes this pass.
    function testBuildFileForTaggedContractWritesToPathForTaggedContract() external {
        string memory tag = "0_1_1$taggedPath";
        cleanup(tag);
        assertFalse(vm.exists("src/generated/0_1_1$taggedPath/LibFsTaggedPath.sol"), "dirty precondition");
        address instance = address(new CodeGennable());

        LibFs.buildFileForTaggedContract(vm, instance, tag, "LibFsTaggedPath", "\n// body\n");

        assertEq(
            LibFs.pathForTaggedContract(tag, "LibFsTaggedPath"),
            "src/generated/0_1_1$taggedPath/LibFsTaggedPath.sol",
            "path disagreement"
        );
        assertTrue(vm.exists("src/generated/0_1_1$taggedPath/LibFsTaggedPath.sol"), "not written to the expected path");
        cleanup(tag);
    }

    /// The first generation for a tag has no directory yet, which is the normal
    /// case for a release: the snapshot directory is created by the run that
    /// fills it. `vm.writeFile` does not create a missing parent, so the
    /// directory creation is load bearing and this is what proves it.
    function testBuildFileForTaggedContractCreatesTheTagDir() external {
        string memory tag = "0_1_1$taggedFreshDir";
        cleanup(tag);
        assertFalse(vm.exists(LibFs.dirForTag(tag)), "tag directory is not fresh");
        address instance = address(new CodeGennable());
        string memory body = "\n// fresh dir\n";

        LibFs.buildFileForTaggedContract(vm, instance, tag, "LibFsTaggedFreshDir", body);

        assertTrue(vm.isDir(LibFs.dirForTag(tag)), "tag directory was not created");
        assertEq(vm.readFile(LibFs.pathForTaggedContract(tag, "LibFsTaggedFreshDir")), expectedFile(instance, body));
        cleanup(tag);
    }

    /// An existing tag directory is written into rather than replaced, so the
    /// snapshot's other files survive a regeneration of one of them.
    function testBuildFileForTaggedContractReusesAnExistingTagDir() external {
        string memory tag = "0_1_1$taggedExistingDir";
        cleanup(tag);
        vm.createDir(LibFs.dirForTag(tag), true);
        vm.writeFile(string.concat(LibFs.dirForTag(tag), "/bystander.txt"), "BYSTANDER");
        address instance = address(new CodeGennable());
        string memory body = "\n// existing dir\n";

        LibFs.buildFileForTaggedContract(vm, instance, tag, "LibFsTaggedExistingDir", body);

        assertEq(
            vm.readFile(string.concat(LibFs.dirForTag(tag), "/bystander.txt")),
            "BYSTANDER",
            "the directory was replaced"
        );
        assertEq(vm.readFile(LibFs.pathForTaggedContract(tag, "LibFsTaggedExistingDir")), expectedFile(instance, body));
        cleanup(tag);
    }

    /// An existing file at the path is replaced, not appended to and not
    /// partially overwritten. The pre-existing content is deliberately longer
    /// than what is generated, so any tail of it left behind fails here.
    function testBuildFileForTaggedContractReplacesExistingContent() external {
        string memory tag = "0_1_1$taggedOverwrite";
        cleanup(tag);
        vm.createDir(LibFs.dirForTag(tag), true);
        string memory stale = "STALE";
        for (uint256 i = 0; i < 8; i++) {
            stale = string.concat(stale, stale);
        }
        vm.writeFile(LibFs.pathForTaggedContract(tag, "LibFsTaggedOverwrite"), stale);
        assertTrue(bytes(stale).length > 1000, "stale content is not long enough to detect a tail");

        address instance = address(new CodeGennable());
        string memory body = "\n// replaced\n";
        LibFs.buildFileForTaggedContract(vm, instance, tag, "LibFsTaggedOverwrite", body);

        assertEq(vm.readFile(LibFs.pathForTaggedContract(tag, "LibFsTaggedOverwrite")), expectedFile(instance, body));
        cleanup(tag);
    }

    /// Generation is idempotent: consumers commit the result and CI regenerates
    /// it, so a second run over the same inputs must produce the same bytes.
    function testBuildFileForTaggedContractIdempotent() external {
        string memory tag = "0_1_1$taggedIdempotent";
        cleanup(tag);
        address instance = address(new CodeGennable());
        string memory body = "\n// idempotent\n";

        LibFs.buildFileForTaggedContract(vm, instance, tag, "LibFsTaggedIdempotent", body);
        string memory first = vm.readFile(LibFs.pathForTaggedContract(tag, "LibFsTaggedIdempotent"));
        LibFs.buildFileForTaggedContract(vm, instance, tag, "LibFsTaggedIdempotent", body);
        string memory second = vm.readFile(LibFs.pathForTaggedContract(tag, "LibFsTaggedIdempotent"));

        assertEq(first, second, "second run differs from the first");
        assertEq(second, expectedFile(instance, body));
        cleanup(tag);
    }

    /// An empty body still produces the prefix and the bytecode hash constant,
    /// which the docstring says are always included. Nothing is substituted for
    /// the missing body.
    function testBuildFileForTaggedContractEmptyBody() external {
        string memory tag = "0_1_1$taggedEmptyBody";
        cleanup(tag);
        address instance = address(new CodeGennable());

        LibFs.buildFileForTaggedContract(vm, instance, tag, "LibFsTaggedEmptyBody", "");

        assertEq(vm.readFile(LibFs.pathForTaggedContract(tag, "LibFsTaggedEmptyBody")), expectedFile(instance, ""));
        cleanup(tag);
    }

    /// The body is concatenated verbatim with no separator inserted in front of
    /// it, and quotes and backslashes in it are not escaped.
    function testBuildFileForTaggedContractBodyVerbatim() external {
        string memory tag = "0_1_1$taggedVerbatim";
        cleanup(tag);
        address instance = address(new CodeGennable());
        string memory body = "string constant S = \"a\\\"b\";\n";

        LibFs.buildFileForTaggedContract(vm, instance, tag, "LibFsTaggedVerbatim", body);

        string memory written = vm.readFile(LibFs.pathForTaggedContract(tag, "LibFsTaggedVerbatim"));
        assertEq(written, expectedFile(instance, body));
        assertTrue(vm.contains(written, "DO NOT EDIT BY HAND.\n\n/// @dev Hash"), "prefix and hash are separated");
        assertTrue(vm.contains(written, ");\nstring constant S ="), "a separator was inserted before the body");
        cleanup(tag);
    }

    /// The whole point of the per tag layout: the same contract generated under
    /// one tag must not disturb the file under another. A frozen snapshot is
    /// only frozen if regenerating the rolling tag leaves it byte for byte
    /// alone.
    function testBuildFileForTaggedContractLeavesOtherTagsAlone() external {
        string memory frozen = "0_1_1$taggedFrozen";
        string memory rolling = "candidate$taggedRolling";
        cleanup(frozen);
        cleanup(rolling);
        address frozenInstance = address(new CodeGennable());
        address rollingInstance = address(this);
        assertNotEq(frozenInstance.codehash, rollingInstance.codehash, "instances must hold different code");
        string memory frozenBody = "\n// frozen\n";

        LibFs.buildFileForTaggedContract(vm, frozenInstance, frozen, "LibFsTaggedShared", frozenBody);
        string memory frozenFile = vm.readFile(LibFs.pathForTaggedContract(frozen, "LibFsTaggedShared"));

        LibFs.buildFileForTaggedContract(vm, rollingInstance, rolling, "LibFsTaggedShared", "\n// rolling\n");

        assertEq(
            vm.readFile(LibFs.pathForTaggedContract(frozen, "LibFsTaggedShared")),
            frozenFile,
            "the frozen snapshot was disturbed"
        );
        assertEq(frozenFile, expectedFile(frozenInstance, frozenBody));
        assertEq(
            vm.readFile(LibFs.pathForTaggedContract(rolling, "LibFsTaggedShared")),
            expectedFile(rollingInstance, "\n// rolling\n"),
            "the rolling snapshot is wrong"
        );
        cleanup(frozen);
        cleanup(rolling);
    }

    /// Generating one contract must not disturb another contract's generated
    /// file within the same tag. A snapshot holds many files.
    function testBuildFileForTaggedContractLeavesSiblingsAlone() external {
        string memory tag = "0_1_1$taggedSiblings";
        cleanup(tag);
        address instance = address(new CodeGennable());
        string memory bodyA = "\n// sibling a\n";
        string memory bodyB = "\n// sibling b\n";

        LibFs.buildFileForTaggedContract(vm, instance, tag, "LibFsTaggedSiblingA", bodyA);
        LibFs.buildFileForTaggedContract(vm, instance, tag, "LibFsTaggedSiblingB", bodyB);

        assertEq(
            vm.readFile(LibFs.pathForTaggedContract(tag, "LibFsTaggedSiblingA")),
            expectedFile(instance, bodyA),
            "sibling a was disturbed"
        );
        assertEq(
            vm.readFile(LibFs.pathForTaggedContract(tag, "LibFsTaggedSiblingB")),
            expectedFile(instance, bodyB),
            "sibling b is wrong"
        );
        cleanup(tag);
    }

    /// The tagged write never touches the untagged file for the same contract
    /// name, so adding a snapshot cannot silently replace a current pin.
    function testBuildFileForTaggedContractLeavesTheUntaggedFileAlone() external {
        string memory tag = "0_1_1$taggedUntagged";
        cleanup(tag);
        address instance = address(new CodeGennable());
        string memory untaggedPath = LibFs.pathForContract("LibFsTaggedUntagged");
        vm.writeFile(untaggedPath, "UNTAGGED");

        LibFs.buildFileForTaggedContract(vm, instance, tag, "LibFsTaggedUntagged", "\n// tagged\n");

        assertEq(vm.readFile(untaggedPath), "UNTAGGED", "the untagged file was disturbed");
        vm.removeFile(untaggedPath);
        cleanup(tag);
    }

    /// The bytecode hash is read from the instance that was passed in, not from
    /// the caller and not from a fixed address. Two addresses holding different
    /// code produce different files.
    function testBuildFileForTaggedContractUsesTheGivenInstance() external {
        string memory tag = "0_1_1$taggedInstance";
        cleanup(tag);
        address instance = address(new CodeGennable());
        address other = address(this);
        assertTrue(instance.code.length > 0 && other.code.length > 0, "both addresses must hold code");
        assertNotEq(instance.codehash, other.codehash, "addresses must hold different code");

        LibFs.buildFileForTaggedContract(vm, instance, tag, "LibFsTaggedInstance", "");
        string memory fromInstance = vm.readFile(LibFs.pathForTaggedContract(tag, "LibFsTaggedInstance"));
        LibFs.buildFileForTaggedContract(vm, other, tag, "LibFsTaggedInstance", "");
        string memory fromOther = vm.readFile(LibFs.pathForTaggedContract(tag, "LibFsTaggedInstance"));

        assertNotEq(fromInstance, fromOther, "instance is not what the hash is read from");
        assertEq(fromInstance, expectedFile(instance, ""));
        assertEq(fromOther, expectedFile(other, ""));
        cleanup(tag);
    }

    /// Removes whatever is at `path`, so that a test asserting nothing was
    /// written there establishes its own precondition rather than assuming one.
    function cleanupPath(string memory path) internal {
        if (vm.exists(path)) {
            if (vm.isDir(path)) {
                vm.removeDir(path, true);
            } else {
                vm.removeFile(path);
            }
        }
    }

    /// A tag that is outside the alphabet gets no path from
    /// `pathForTaggedContract`, and `buildFileForTaggedContract` asks for the
    /// path before it reaches a cheatcode, so the refusal arrives before
    /// anything is written.
    function assertTagRejected(string memory tag, string memory contractName) internal {
        vm.expectRevert(abi.encodeWithSelector(InvalidTag.selector, tag));
        iExternal.buildFileForTaggedContract(vm, address(this), tag, contractName, "");
    }

    /// A contract name that is not a Solidity identifier is refused the same
    /// way.
    function assertNameRejected(string memory tag, string memory contractName) internal {
        vm.expectRevert(abi.encodeWithSelector(InvalidContractName.selector, contractName));
        iExternal.buildFileForTaggedContract(vm, address(this), tag, contractName, "");
    }

    /// An empty tag would write to `src/generated//Foo.sol`, which resolves to
    /// the untagged file. Refused, and the untagged file does not appear.
    function testBuildFileForTaggedContractRejectsEmptyTag() external {
        cleanupPath("src/generated/LibFsTaggedEmptyTag.sol");
        assertTagRejected("", "LibFsTaggedEmptyTag");
        assertFalse(vm.exists("src/generated/LibFsTaggedEmptyTag.sol"), "an empty tag still wrote a file");
    }

    /// A separator in the tag reaches a deeper directory, which the `read-write`
    /// grant on the generated directory admits, so the refusal has to come from
    /// the library.
    function testBuildFileForTaggedContractRejectsSubdirectoryTag() external {
        cleanupPath("src/generated/sub");
        assertFalse(vm.exists("src/generated/sub"), "dirty precondition");
        assertTagRejected("sub/0_1_1", "LibFsTaggedSubTag");
        assertFalse(vm.exists("src/generated/sub"), "a separator still created a subdirectory");
    }

    /// A relative directory reference in the tag leaves the generated directory
    /// entirely. Under this repo's `fs_permissions` the write is refused anyway,
    /// but under the `read-write` grant on `.` that consumers commonly write it
    /// is not, so the refusal has to come from here.
    function testBuildFileForTaggedContractRejectsTraversalTag() external {
        assertTagRejected("..", "LibFsTaggedTraversalTag");
        assertTagRejected("../../ESCAPED", "LibFsTaggedTraversalTag");
    }

    /// A separator in the contract name reaches a directory below the tag's, and
    /// `..` climbs back out of it onto an untagged file.
    function testBuildFileForTaggedContractRejectsNameEscapes() external {
        cleanupPath("src/generated/0_1_1$taggedNameEscape");
        assertNameRejected("0_1_1$taggedNameEscape", "");
        assertNameRejected("0_1_1$taggedNameEscape", "sub/LibFsTaggedNameEscape");
        assertNameRejected("0_1_1$taggedNameEscape", "..");
        assertNameRejected("0_1_1$taggedNameEscape", "../LibFsTaggedNameEscape");
        assertNameRejected("0_1_1$taggedNameEscape", "LibFsTaggedNameEscape.sol");
        assertFalse(vm.exists("src/generated/0_1_1$taggedNameEscape"), "a rejected name still created the tag dir");
    }

    /// Every tag outside the alphabet is refused, not just the ones named above.
    function testBuildFileForTaggedContractRejectsEveryNonTag(bytes memory tagBytes) external {
        string memory tag = string(tagBytes);
        vm.assume(!LibCodeGenSlow.isTagSlow(tag));
        assertTagRejected(tag, "LibFsTaggedFuzzTag");
    }

    /// Every contract name that is not a Solidity identifier is refused, not
    /// just the ones named above.
    function testBuildFileForTaggedContractRejectsEveryNonIdentifierName(bytes memory nameBytes) external {
        string memory contractName = string(nameBytes);
        vm.assume(!LibCodeGenSlow.isContractNameSlow(contractName));
        assertNameRejected("0_1_1$taggedFuzzName", contractName);
    }
}
